# Generated by Django 4.2 on 2023-04-28 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
