# Generated by Django 4.2 on 2023-04-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='followers',
            new_name='participants',
        ),
    ]
