# Generated by Django 3.2.7 on 2023-01-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230124_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status_color',
            field=models.CharField(choices=[('primary', 'Primary'), ('info text-dark', 'Info text-dark'), ('danger', 'Danger'), ('warning text-dark', 'Warning text-dark')], default='primary', max_length=50),
        ),
    ]
