# Generated by Django 4.1.5 on 2023-02-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_post_status_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="posts/default.jpg", upload_to="posts/"),
        ),
    ]
