# Generated by Django 4.1.5 on 2023-02-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_auto_20200729_0442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
